#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/fft_ramdq/fftfull}]} {
  file mkdir {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/fft_ramdq/fftfull}
}
cd {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/fft_ramdq/fftfull}

sys_set_attribute -gui on -msg {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/fft_ramdq/promote.xml}
msg_load {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/fft_ramdq/promote.xml}
des_set_project_udb -in {fft_ramdq_fftfull_syn.udb} -out {fft_ramdq_fftfull_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false }
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
