#-- Lattice Semiconductor Corporation Ltd.
#-- Place & Route run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft}]} {
  file mkdir {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft}
}
cd {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft}

sys_set_attribute -gui on -msg {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/promote.xml}
msg_load {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/promote.xml}
des_set_project_udb -in {proj_fft_fft_map.udb} -out {proj_fft_fft.udb} -milestone par -pm ice40tp
des_set_reference_udb -clean
# par option
par_set_option { disable_timing_driven false placement_iterations 1 placement_iteration_start_point 1 placement_save_best_run "1"  number_of_host_machine_cores "1" path_based_placement on  stop_once_timing_is_met false   set_speed_grade_for_hold_optimization m disable_auto_hold_timing_correction false prioritize_hold_correction_over_setup_performance false run_placement_only false impose_hold_timing_correction false}
# run place & route
par_run
# backup netlist & constraint file
if {[file exists {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft_syn.udb}] && [file exists {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft_map.udb}] && [file exists {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft.udb}]} {
  file delete -force {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/proj_fft_fft_syn.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/proj_fft_fft_map.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/proj_fft_fft.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/lastrun.pdc}
  file copy -force -- {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft_syn.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/postsyn.udb}
  file copy -force -- {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft_map.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/postmap.udb}
  file copy -force -- {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/proj_fft_fft.udb} {C:/Users/User/Desktop/Engr 155/e155-final-project/fpga/radiant_project/proj_fft-20251117T072402Z-1-001/proj_fft/fft/incr/postpar.udb}
}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
