/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.1.0.39.0
    Soft IP Version: 2.4.0
    2025 11 17 23:15:20
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ramdq (clk_i, rst_i, clk_en_i, rd_out_clk_en_i, wr_en_i, wr_data_i,
    addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  clk_en_i;
    input  rd_out_clk_en_i;
    input  wr_en_i;
    input  [35:0]  wr_data_i;
    input  [8:0]  addr_i;
    output  [35:0]  rd_data_o;
endmodule